spring:
    profiles: sushi
    
    datasource:
       url: jdbc:postgresql://localhost/regsystem
       username: james
       password: 12345
server:
    port: 8080
    
---

spring:
    profiles: shawarma
    
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
        password: sa
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
